//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiehausResume.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiehausResume.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutMe_Pic {
            get {
                object obj = ResourceManager.GetObject("AboutMe_Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutMe_picAlt {
            get {
                object obj = ResourceManager.GetObject("AboutMe_picAlt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher ( Chris ) L. Niehaus
        ///
        ///Phone: 636-432-3355
        ///Age: 34
        ///Address: 325 Nottingham Dr Marthassville Mo, 63357
        ///
        ///Education: UMSL | Undergraduate BS Information Systems.
        /// </summary>
        internal static string AboutMeSection {
            get {
                return ResourceManager.GetString("AboutMeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CNIcon {
            get {
                object obj = ResourceManager.GetObject("CNIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developmental Service of Franklin County
        ///104 South McKinley, Union MO 63084
        ///
        ///Start Date:  10/27/2010
        ///End Date: 2/3/2016
        ///Phone:  636-583-5801
        ///
        ///Job Description: Direct Service Professional
        ///	This was my first position while working at DSFC.  I worked with individuals with disabilities in their home.  My main job was to keep track on each clients money and to provide everyday care to the clients. 
        ///
        ///Job Description: Behavior Intervention Technician
        ///	This position was my second at DSFC.  I worked prima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSFC {
            get {
                return ResourceManager.GetString("DSFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emmaus Homes Inc. 
        ///11900 Emmaus Dr, Marthasville, MO 63357 (This location is closing and has since merged with the St. Charles location)
        ///
        ///New Address: 3731 Mueller Road St. Charles, MO 63301
        ///
        ///Start Date:  8/8/2004
        ///End Date:  11/10/2010
        ///Phone: 636.534.5200
        ///
        ///Job Description: Direct Care Support
        ///	Worked with five individuals in one home.  Each of my clients had dual diagnosis and I worked with several disorders that included schizophrenia, bi-polar, borderline personality, explosive personality, auti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Emmaus {
            get {
                return ResourceManager.GetString("Emmaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - I am married and have two daughters agess 4 and 6
        ///
        ///- My oldest has a learning disability so my time off work is devoted to teaching her skills
        ///
        ///- We live in Lake Sherwood MO 
        ///.
        /// </summary>
        internal static string FamilySection {
            get {
                return ResourceManager.GetString("FamilySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Gaming- Particularly games under development such as ARK, Oxygen Not Included, Subnautica
        ///
        ///- Wood Turning- Currently learning skills with the intention to make fountain pens
        ///
        ///- House Work- Drywall, electric, painting, yard work, rock facing, plumbing
        ///
        ///- Backpacking- Over 500 miles, parks all over MO, TN, and KY
        ///
        ///- Camping/Floating- Huge passion, we go mainly to the Black River area in Lesterville MO.
        ///
        ///- Beach Time- We have a neighborhood beach and frequently go swimming
        ///
        ///- Programming- Several [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HobbiesSection {
            get {
                return ResourceManager.GetString("HobbiesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Missouri St. Louis
        ///1 University Blvd. St. Louis, MO 63121-4400
        ///
        ///Start Date: Pending | Summer &amp; Fall 2017
        ///
        ///Job Description:
        ///	Tutor for C# and assistant to Professor Brian Boyer.  .
        /// </summary>
        internal static string UMSL {
            get {
                return ResourceManager.GetString("UMSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UMSL_Logo {
            get {
                object obj = ResourceManager.GetObject("UMSL_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
